language: python
python:
  - '3.7'

before_install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
- mkdir geckodriver && tar zxvf geckodriver-v0.16.0-linux64.tar.gz -C geckodriver
- export PATH=$PATH:$PWD/geckodriver

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre_project.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
