language: python
python:
  - '3.7'

addons:
  apt:
    packages:
      firefox-geckodriver

before_install:
- export PATH=$PATH:/usr/local/bin

before_script:
  - pip install -r requirements.txt


branches:
  only:
    - staging

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre_project.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
